### ISSUE TITLE
Names for primitive State/Writer flavors

### ISSUE THREAD

**Issue by arybczak** [arybczak/effectful#18]
There are two primitive `State` (and `Writer`) flavors, the thread-local version (`Effectful.State`) and shareable version (`Effectful.State.MVar`).

I think module names could be better. My current favorite is `Effectful.State.Local` and `Effectful.State.Shared`. Does that sound reasonable?

Looks good to me, except for the slightly annoying fact that `L` and `S` typically stand for lazy and strict and here it would be local and shared.

**Comment by mmhat** [comment]
Sounds good to me. Intuitively I'd abbreviate those modules with `SL` and `SS`; Hence I don't have problems with that.

**Comment by theophile-scrive** [comment]
Same, if you write in the documentation / examples `import qualified Effectful.State.Shared as Shared` and warn about ambiguity, people will get the habit of using those prefixes instead of `S.` and `L.`.

**Comment by arybczak** [comment]
I did this in cee28d5c510b65c226c198994a3514a2abba288b. Now however I wonder whether it should be `Shared` or `Global` :thinking: :joy:

**Comment by mmhat** [comment]
> I wonder whether it should be `Shared` or `Global`

I think `Shared` is ok :smile:
