### ISSUE TITLE
Consistent naming of effects

### ISSUE THREAD

**Issue by mmhat** [arybczak/effectful#23]
Right now we ship effects with two different naming conventions: Some are suffixed with 'E' (like `AsyncE`) and some are not (like `Reader`). We may consider renaming the effects of one of the two groups in order to have a uniform naming scheme.

**Comment by mmhat** [comment]
Personally I prefer the 'E' suffix for two reasons: The effects are easier to recognize and there are less name collisions with other libraries. (I guess that's why `AsyncE` was named that way in the first place).

**Comment by arybczak** [comment]
There's:
- `IOE` because `IO` is a monad
- `AsyncE` because `Async` represents async actions
- `STME` because `STM` is a monad

There's also a newly added `PrimE`, but arguably it should be `Prim` because it doesn't conflict with anything.

I don't particularly like the `E` suffix and wouldn't want to have `ReaderE`, `StateE` etc :thinking: It's just that for the above three I didn't have a better idea how to name them.

**Comment by arybczak** [comment]
In theory for conflicting types there could be a poly kinded adapter:

```haskell
data family E (a :: k) :: Effect

newtype instance E IO :: Effect where
  IOE :: UnliftStrategy -> E IO m r

data instance E Async :: Effect where
  AsyncE :: E Async m r

data instance E S.STM :: Effect where
  STME :: E S.STM m r

runIO :: Eff '[E IO] a -> IO a
runIO m = unEff (evalEffect (IdE (IOE SeqUnlift)) m) =<< emptyEnv

runAsync :: E IO :> es => Eff (E Async : es) a -> Eff es a
runAsync = evalEffect (IdE AsyncE)

runSTM :: E IO :> es => Eff (E S.STM : es) a -> Eff es a
runSTM = evalEffect (IdE STME)
```

But I'm not sure if it's a good idea.

**Comment by mmhat** [comment]
IMHO the poly kinded adapter does not give us any more consistency compared to the current naming. I have to admit that it took me some time (and having written half a dozen effects) I got used to it and started to value consistency more than the dangling 'E'.

> I don't particularly like the `E` suffix and am not a fan of `ReaderE`, `StateE` etc

Judging from that and [this](https://github.com/arybczak/effectful/pull/22#issuecomment-877633712) comment I guess this is a "won't fix"?

**Comment by arybczak** [comment]
I don't know yet 🤔

**Comment by arybczak** [comment]
Ok, currently we have the following effects:

```
AsyncE
Error
Fail
IOE
Prim
Reader
State
Writer
```

From these only `IOE` and `AsyncE` has the suffix (there's also `STME` but I want to get rid of it). Now, I wanted to eventually have things at leasty from `unliftio` divided into effects. Here's a list of modules from `unliftio`, name in parentheses is a proposition for the effect:

```
Chan (Conc)
Concurrent (Fork)
Directory (Directory)
Environment (Env)
Foreign (FFI)
IORef (Var)
MVar (Conc)
Process (Process)
QSem (Conc)
QSemN (Conc)
STM (Conc)
Temporary (Temporary)
Timeout (Timeout)
```

Arguably `AsyncE` can be subsumed by `Conc` at this point. Then it's only `IOE` that needs the suffix.

Application-specific effects written by users also shouldn't collide with existing things :thinking:

**Comment by mmhat** [comment]
> Perhaps you encountered more collisions in your code?

Not  really, but I did have a `Reader` and a `Writer` in my code base :slightly_smiling_face:
I started using the 'E' suffix for the same reason as you did: I had a `Storage` object I am passing around but I wanted to have a `Storage` effect, too. Hence I went with `StorageE`. At some point a introduced some more effects like that and suddenly the 'E' was not so exceptional anymore. As a consequence I added the 'E' suffix to all my custom effects.

So for me it is really more a convenience issue:
If I read some code and encounter some `ReaderT`, `LoggingT`, `WhateverT` type I can assume that it has a `MonadTrans` instance,  kind `(Type -> Type) -> Type -> Type` and so on. It seems that the 'L' suffix is quite popular among lens users.
So it is really more about giving some context to an identifier.

Regarding the propositions for effect names: I am not sure if `Env`, `Var` and `Process` are to generic or widely used. At least the `Env` and `Var` get quite some hits on Hoogle.

**Comment by mmhat** [comment]
Hm, I got second thoughts about the proposed 'E' suffix: It does not seem to be that common in other effect libraries and I have to admit that the code looks nicer from an aesthetic point of view if there isn't camel case all over the place.
That being said, I changed my opinion on this topic: Let's stick with what is common (I.e. no 'E' suffix) to the domain of the library (I.e. effect systems).

Furthermore, I do think clashing names are ok from the point of view of this library and we shouldn't care to much about it: There is always the possiblity of qualified imports and most sophisticated applications come with a custom prelude anyway which is IMHO the right place to deal with naming issues.
That being said I'd go with the following:

1. Get rid of the `AsyncE` effect in favor of a broader `Conc` or `Concurrent` effect.
2. Leave `IOE` as the one great exception.

Regarding your proposal:
1. `Chan`, `MVar`, `QSem`, `QSemN`: I am not sure if those should be `Conc` (or `Concurrent`) since they don't introduce concurrency. They're more about mutable state (Maybe a `MutableState` effect? :thinking: ) in a concurrent setting. TBH, am not even sure if those should have an own effect or if that is `IOE`...
2. Isn't `FFI` more of an implementation detail? Intuitively I'd say that is covered by `IOE`.
3. `Temporary` is really just `FileSystem`
4. I really like the `FileSystem`, `Process`, `Environment` and `Timeout` effects. :+1: 

BTW: Should we use abbreviations when choosing our effect names? For example: `Conc`  vs. `Concurrent`; `Env` vs. `Environment`; `Prim` vs. `Primitive`?

**Comment by expipiplus1** [comment]
Just a reminder before closing this issue: It'd be great to have whatever naming scheme documented in the readme to help guide people defining custom effects use the correct name.

**Comment by arybczak** [comment]
I'm still unsure about this. E.g. #25 exposes the clash between `Process` (the effect) and `Process` (the data type representing the process).

It the rule "use no suffix unless there is a name collision with a type related to things you're wrapping in an effect" really that bad?

**Comment by arybczak** [comment]
Closing since the only effect with the E suffix is `IOE` now.
