### ISSUE TITLE
Storing ecosystem libraries

### ISSUE THREAD

**Issue by Kleidukos** [arybczak/effectful#24]
Hi! I took the liberty of creating a repository called [effectful-contrib](https://github.com/Kleidukos/effectful-contrib) where I stored my bindings to libraries like `time` and `cache`.

**Comment by arybczak** [comment]
Thanks for letting me know :slightly_smiling_face:

As I already described in https://github.com/arybczak/effectful/pull/25#issuecomment-887091564, I'd like to avoid a situation in which I have too much code to maintain, so I'm leaning towards simply having this repository for the core, i.e. `effectful-core`, `effectful` and `effectful-resourcet`, while letting people store their `effectful` contrib libraries where they see fit.

That's the approach taken by `optics` and it seems to work well.

You suggested an `effectful` organization for storing the core and contrib libraries, but I suppose that would require me to coordinate access rights, which is the burden I'm not quite keen on taking :thinking:

**Comment by Kleidukos** [comment]
Absolutely understandable! Focus on the lib, I'll take care of upgrading the bindings every once in a while until stable releases. ;)
