### ISSUE TITLE
Merging (re)interpret and (re)interpretM

### ISSUE THREAD

**Issue by arybczak** [arybczak/effectful#26]
Is it a good idea to rename current `(re)interpretM` to `(re)interpret` and get rid of the simpler variant?

On one hand it makes the API simpler, on the other people will have to ignore the `LocalEnv` parameter themselves when handling first order effects.

**Comment by evanrelf** [comment]
Assuming it's only about an extra parameter, and not any difference in type inference, I slightly prefer the simpler API with fewer functions.

I think mentioning how `LocalEnv` is unnecessary for first order effects in the docs, and/or having lots of examples in the library source to cargo cult off of, is enough to clear up confusion regarding the `LocalEnv` parameter.

**Comment by arybczak** [comment]
Ok, I merged them, let's see how it goes. Thanks for the opinion @evanrelf :slightly_smiling_face:
