### ISSUE TITLE
Is it possible to run Eff computations purely (or in ST)?

### ISSUE THREAD

**Issue by expipiplus1** [arybczak/effectful#3]
Something like

```haskell
runEff :: Eff '[] a -> a
runEffIO :: Eff '[IOE] a -> IO a
```

This certainly seems quite contrary to how Eff is defined internally.

Is it true to say that `unsafePerformIO . runEff` is not unsafe when given an `Eff` without the `IOE` effect (and any use of `unsafeEff`?

**Comment by arybczak** [comment]
Making `runEff` use `unsafePerformIO` (or even `unsafeDupablePerformIO`) *should* be safe, but I'm not 100% sure :thinking:

**Comment by expipiplus1** [comment]
And what about `runIOE :: Eff (IOE : es) a -> IO (Eff es a)`?

**Comment by arybczak** [comment]
That would make it possible to introduce `IOE` at any point in `Eff`.

**Comment by expipiplus1** [comment]
Thanks!
