### ISSUE TITLE
Tests for the `Environment` effect don't work in a multithreaded setting

### ISSUE THREAD

**Issue by mmhat** [arybczak/effectful#39]
The failures are observed [here](https://github.com/arybczak/effectful/pull/38/checks?check_run_id=3809415191) and [here](https://github.com/arybczak/effectful/pull/38/checks?check_run_id=3809415253).
Note that the tests are not failing consistently.

**Comment by arybczak** [comment]
These tests fail intermittently even if original functions from `System.Environment` are used.

It looks like `System.Environment` is simply broken when used from multiple threads (as tests run using 4 threads by default). It causes intermittent test failures or even segfaults (!). By forcing `-N1` (or removing Environment test from the testsuite) these disappear.

**Comment by mmhat** [comment]
Uh, those are bad news :unamused: .
I guess we are hit by [this](https://gitlab.haskell.org/ghc/ghc/-/issues/18261) bug (and maybe [this](https://gitlab.haskell.org/ghc/ghc/-/issues/18418) one is related as well).
We could try to run the `test_withArgs` and the `test_withProg` tests sequentially; Maybe that helps.

**Comment by arybczak** [comment]
> However, that does not explain why removing the threadDelay in test_asyncWithUnmask causes the failure...

It just makes it easier to trigger by executing tests faster in a loop.

The solution is to compress all 4 tests into one, then there are no concurrent invocations to functions from `System.Environment` from multiple threads and all should be well.
