### ISSUE TITLE
Morality of (un)lifting functions

### ISSUE THREAD

**Issue by re-xyr** [arybczak/effectful#41]
I noticed that `localUnlift` does not have an `IOE` effect constraint while `localUnliftIO` does, which is understandable. However `localLiftUnlift` also has `IOE`, which implies that lifting is not as reasonable as unlifting.

As I could imagine, the interpreting environment `es` should be strictly smaller than the sending environment `localEs`, i.e. it would be logically trivial to lift `es` into `localEs`. Or am I missing something?

**Comment by arybczak** [comment]
Thanks for noticing, these constraints shouldn't have been there, I removed them.
