### ISSUE TITLE
`listen` does not accumulate the main writer value in real time

### ISSUE THREAD

**Issue by re-xyr** [arybczak/effectful#44]
Currently, in the shared Writer effect, the `listen` operation creates a new `MVar` for the action to write, and the content is only appended to the main `MVar` after the action finishes (or throws). This means the content being written is no longer real time.

Is this a problem?

**Comment by re-xyr** [comment]
Also - is `pass` not there because we don’t know what to do if the action threw an exception?

**Comment by arybczak** [comment]
Yes, exactly. Both `pass` and `censor` do not play well with exceptions, so they're omitted. Nobody uses them anyway as far as I know.

**Comment by re-xyr** [comment]
I found that `eff` employs a different semantics for `censor` - it applies the function to *each output*. So `censor f (tell a >> tell b)` becomes `tell f a >> tell f b`. `MonadWriter` is lawless, so this semantics makes sense; it also does not violate the laws [others tried to add](https://hackage.haskell.org/package/capability-0.5.0.0/docs/Capability-Writer.html#t:HasWriter). This *may* be an idea worth investigation, though I'd recommend giving it another name in order not to make users confused.

But I agree - `pass` is *really* weird. It wasn't mentioned in the original monad transformers paper too, so my (handwavy) guess is some people back in the 2000s added it just for a fancier look. `censor` makes slightly more sense, but not that much.

**Comment by arybczak** [comment]
As for the original issue, the description of `listen` says

> Execute an action and append its output to the overall output of the 'Writer'.

which is exactly what the current implementation does. The value is accumulated "on the side", then applied to the overall output at the end.

It's possible to make `listen` apply values to the output at once, but then it would have to keep track of things it has to return at the end separately, making it do all mappendS twice, which isn't very enticing.
