### ISSUE TITLE
Potential O(n) lookup of dynamic effects?

### ISSUE THREAD

**Issue by re-xyr** [arybczak/effectful#46]
When a dynamic effect is interpreted, the `Env` is forked (which is O(1)). This means with every extra handler, previous handlers are one layer deeper in the `Forks` structure. Therefore time of access to these handlers increase linearly, hence O(n) lookup. Of course, this does not apply to static dispatch.

Considering the number of effects on an effect stack typically won't be large, I'm not sure if this is a serious problem in practice. Maybe I'll construct an edge case benchmark later. But at least, `Env` is not amortized O(1) in worst cases.

**Comment by arybczak** [comment]
> But at least, Env is not amortized O(1) in worst cases.

The complexities are [here](https://github.com/arybczak/effectful/blob/04aa70d8a5aa56fb016469c05be3981c67ad37b1/effectful-core/src/Effectful/Internal/Env.hs#L48).

> This means with every extra handler, previous handlers are one layer deeper in the Forks structure.

Yes, but that only affects the environment inside the handler. As an example let's consider the environment portrayed [here](https://github.com/arybczak/effectful/blob/04aa70d8a5aa56fb016469c05be3981c67ad37b1/effectful-core/src/Effectful/Internal/Env.hs#L61):

```
e00 - e01 - e05 - e07 (*)
       |     |     |
       |    e06   e08 - e09
       |
      e02 - e03
             |
            e04
```

the environment seen by (each bracket is a fork):

* the handler of `e03` is `[e00][e02][e04]`
* the handler of `e01` is `[e00][e02, e03]`
* the mainline is `[e00, e01, e05, e07]` (the mainline never has forks).

So in two most common cases (sending an operation from the mainline or sending an operation of the reinterpreted effects from the effect handler) the dispatch is `O(1)`.
