### ISSUE TITLE
Compiler panic with GHC 9.0.1

### ISSUE THREAD

**Issue by mmhat** [arybczak/effectful#47]
Observed in an CI failure of the [effectful-contrib](url) repository. The relevant commit is https://github.com/mmhat/effectful-contrib/commit/1c61d787a0b06d24602112ed03b6160bc213f7bd
and the failure is in https://github.com/Kleidukos/effectful-contrib/runs/4682024344.

**Comment by mmhat** [comment]
I am not sure if this is a known issue or not. I noticed that GHC 9.0.1 already got removed from the CI setup in https://github.com/arybczak/effectful/commit/bc05397c85d0fcbcb2c56a5b440444e3a48b471b.
If the library does not work with GHC 9.0.1 (anymore) then we should probably add something like
```cabal
if impl(ghc >= 6.6.1)
  buildable: false
```
to `effectful-core`s cabal file.

**Comment by arybczak** [comment]
> I am not sure if this is a known issue or not.

Yes. 9.0.2 works, it will be added to CI once ghcup supports it.

**Comment by arybczak** [comment]
Added in 6632678e2f39e6bdc371f77050d56f3716ac7e6f.
