### ISSUE TITLE
Rethrowing errors

### ISSUE THREAD

**Issue by mmhat** [arybczak/effectful#5]
Consider some code like this:
```
runWithCleanup :: Effectful.Error.Error MyException :> es => Eff es a
runWithCleanup = someSubsystem `Effectful.Error.catchError` \cs e -> do
    runSomeCleanup
    Effectful.Error.throwError (e :: MyException)
```
Now the original call stack passed to the handler is gone. While we could write some boilerplate to preserve it (say, a custom exception type) I feel this use case should be supported by the library.

**Comment by arybczak** [comment]
If you need cleanup, then you should use `bracket`/`finally`/`onException` family of functions from the `exceptions` library so that you are guarded from all potential early exit points from the computation.

Presumably if you're explicitly catching the error, then you know how to proceed without immediately rethrowing it :thinking:

**Comment by mmhat** [comment]
> If you need cleanup, then you should use `bracket`/`finally`/`onException` family of functions from the `exceptions` library so that you are guarded from all potential early exit points from the computation.

Ah, yes, I opened that issue under the false assumption that the Error effect is usable for exception handling in general.

> Presumably if you're explicitly catching the error, then you know how to proceed without immediately rethrowing it

That is true for an application author but not for one of a library. Have a look at a modified version of the 'runWithCleanup' function which we provide to some user:
```
runWithCleanup :: Effectful.Error.Error MyException :> es => Eff es a -> Eff es a
runWithCleanup k = k `Effectful.Error.catchError` \cs e -> do
    runSomeCleanup
    Effectful.Error.throwError (e :: MyException)
```
Now if look at the calling site
```
usage = runWithCleanup somethingGoesWrongHere `Effectful.Error.catchError` \cs e -> do
    displayThatStackTrace cs
    doSomethingElse
```
the user will get the impression that the error happend in our (library) code which is misleading.
Or am I missing something here?

**Comment by arybczak** [comment]
Yes, but the point is that you'd never write this code like this, you'd use `onException` or `finally` instead.

**Comment by mmhat** [comment]
Ah, ok, now I got it :-) Thank you!
