### ISSUE TITLE
Module names for static vs dynamic effects

### ISSUE THREAD

**Issue by arybczak** [arybczak/effectful#50]
Copy of https://github.com/arybczak/effectful/pull/49#issuecomment-1007436784 to continue the discussion here as it's unrelated to the PR.

@ilyakooo0

> > Are you referring to State and Writer flavors? That's a different thing, dynamic/static is about dispatch, local/shared is about behavior when multiple threads are spawned within the Eff monad (see this for more details). In principle the modules could be renamed to Effectful.State.Static.Local etc., but I'm not sure about that.
> 
> 
> Yeah, I see that. What "shared" meant was quite evident. The confusion arose in my head at the point where I saw `Effectful.State.Dynamic` and by looking at the code it was obvious that it had the implementation of the dynamically dispatched state effect. Right next to it I saw `Effectful.State.Local`. The name made me slightly confused, but looking at the code it became obvious that it was a simple implementation of a statically dispatched state effect.
> 
> ---
> 
> I think that by the design of the library you get the duality of an effect having two different dispatch methods. I think it would be better to make it obvious what is the static counterpart for what dynamic effect.
> 
> Seeing three state effects one of which is clearly dynamic and the two others not being obvious creates some confusion IMO.
> 
> I think it would be a lot clearer to have:
> 
> ```
> Effectful.State.Dynamic
> Effectful.State.Static.Local
> Effectful.State.Static.Shared
> ```
> 
> Or alternatively, you could have the "root" module of the effect contain the dynamic effect (the interface), and have the "child" modules be the static (base) implementations of the effect:
> 
> ```
> -- | the dynamic effect (interface of the state effect)
> Effectful.State 
> 
> -- | the static effects (implementations of the state effect)
> Effectful.State.Local
> Effectful.State.Shared
> ```

**Comment by ilyakooo0** [comment]
I think this issue should be closed before the next release

I think the next step is for @arybczak to form an opinion on what I have proposed above

**Comment by arybczak** [comment]
> Or alternatively, you could have the "root" module of the effect contain the dynamic effect (the interface), and have the "child" modules be the static (base) implementations of the effect:

The problem here is that `Error` and `Reader` do the opposite, i.e. the root is static. The thing is that I don't really expect people to use the dynamic versions of "built-in" effects in their code the vast majority of time, as:
- `Error` doesn't leave much choice for alternate interpretations
- `State`/`Reader`/`Writer` will mostly be used as private effects for user-defined effects, where the user knows what flavor they want so they can pick the static variant.

Given that I'd be a bit weird to make dynamic versions roots :thinking: 

But if so, then how do `Error` and `Reader`module names change? `Effectful.Error.Static` and `Effectful.Reader.Static` are a possibility, but given they will be used the vast majority of time, it's a bit unfortunate.

**Comment by ilyakooo0** [comment]
> The problem here is that Error and Reader do the opposite, i.e. the root is static.

I am advocating for consistency above all. If `Reader` only has a static dispatch version, I think it's perfectly fine for there to be `Effectful.Reader.Static` as the only module without a "root" module.

---

> The thing is that I don't really expect people (in particular, myself) to use the dynamic versions of "built-in" effects 

Personally, I think that the operations in `Reader` should not have a monoid constraint and the concatenation operation should be specified at the interpretation time (in `runReader`). This seems like a very reasonable use for a dynamic reader.

This is just an example of how a dynamic version might be useful.

**Comment by ilyakooo0** [comment]
IMO it should be easy to understand what exactly the module is importing from its' name and it should be easy to find a module that does what you want (or find out that there is no module that does what you want)

**Comment by ilyakooo0** [comment]
plus, having a consistent hierarchy seems more forward-compatible to me. Adding a dynamic dispatch reader would be easier if the static dispatch version is not taking up the module name.

**Comment by arybczak** [comment]
> Adding a dynamic dispatch reader would be easier if the static dispatch version is not taking up the module name.

The dynamic `Reader` is in `Effectful.Reader.Dynamic`, same for `Error` (`Effectful.Error.Dynamic`).

**Comment by ilyakooo0** [comment]
> The dynamic Reader is in Effectful.Reader.Dynamic, same for Error (Effectful.Error.Dynamic).

Sorry, my bad (:

I slightly misunderstood you.

Are you saying that you prefer having the most commonly used modules be the "root" module of the effect?

**Comment by arybczak** [comment]
> Are you saying that you prefer having the most commonly used modules be the "root" module of the effect?

Yes.

But perhaps I should just bite the bullet and make module names for built-in effects in `effectful-core` that have both static and dynamic versions prefixed:

- `Effectful.Error.Dynamic`
- `Effectful.Error.Static`
- `Effectful.Reader.Dynamic`
- `Effectful.Reader.Static`
- `Effectful.State.Dynamic`
- `Effectful.State.Static.Local`
- `Effectful.State.Static.Shared`
- `Effectful.Writer.Dynamic`
- `Effectful.Writer.Static.Local`
- `Effectful.Writer.Static.Shared`

Especially since I'd like to add another variant of `Writer` that is efficient for accumulation of arbitrary values as it would use `MutableArray` underneath, but I already started wondering what module name to put it in. `Effectful.Writer.Static.Accum` or something similar sounds alright.

Of course that leaves `Effectful.Fail` and `Effectful.Prim`, but they are unique in a sense, so no point in a prefix there.

**Comment by ilyakooo0** [comment]
That sounds like a very reasonable direction to go :+1:
