### ISSUE TITLE
Small-ish Example

### ISSUE THREAD

**Issue by drewolson** [arybczak/effectful#51]
👋 hello! I've made a small-ish example of using [effectful with scotty](https://github.com/drewolson/effectful-scotty-example). I'm not sure if it's something you'd like to link to, or maybe include in the docs or something. Or you can just take the whole example and use it in your examples as well!

Or just do nothing with it. Let me know!

**Comment by arybczak** [comment]
Thanks :slightly_smiling_face: However, I think the example is small enough that other examples already in-place (i.e. in the haddocks) are sufficient for now.
