### ISSUE TITLE
Dynamic version of the Error effect

### ISSUE THREAD

**Issue by arybczak** [arybczak/effectful#53]
Is it even needed? The implementation in `Effectful.Error.Static` is arguably the only one possible, given the interface.

**Comment by ilyakooo0** [comment]
A `thrwoIO`-based implementation might also be useful. (maybe even more efficient?)

**Comment by arybczak** [comment]
Yeah, it's the one in `Effectful.Error.Static` that I'm talking about ;)

**Comment by ilyakooo0** [comment]
I think even if you don't think it is useful now, I feel like having it at least for consistency isn't a bad thing. I don't think we really lose anything by including it.

**Comment by arybczak** [comment]
That's true, I'm just wondering how to best document it.

**Comment by ilyakooo0** [comment]
I think honestly saying that you couldn't think of a use for it at the time of writing would be beneficial (:
